
# Project Identification
sonar.projectKey=SebaranAlumni
sonar.projectName=SebaranAlumni
sonar.projectVersion=1.0

# Project Source Information
sonar.sources=.
sonar.language=php
sonar.sourceEncoding=UTF-8

# Include only specific files and folders
sonar.inclusions=\
app/Guards/,\
app/Http/,\
resources/views/alumni/mahasiswa/sebaran-alumni.blade.php,\
resources/data/,\
public/css/,\
public/js/map-init.js,\
public/images/,\
public/geojson/,\
app/Http/Controllers/AlumniController.php,\
app/Http/Controllers/MahasiswaController.php,\

# SonarQube Server Authentication and URL
sonar.host.url=http://localhost:9000
sonar.token=sqp_15ea475ef6fb2a2753e5e667b391b710e2a3eaff

